### ISSUE TITLE
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("keras_learning_phase:0", dtype=bool) is not an element of this graph.

### ISSUE THREAD

**Issue by asbonatto** [asbonatto/CarND-Capstone#1]
There are some hints here 
https://stackoverflow.com/questions/40785224/tensorflow-cannot-interpret-feed-dict-key-as-tensor

**Comment by FabianHertwig** [comment]
Got a similiar error. To fix that save the graph after loading the net:

    self.model = load_model(...)
    self.graph = tf.get_dafault_graph()    


and then when predicting:
    
    with self.graph.as_default():
        self.model.predict(...)
